canales:
    pattern:  /
    defaults: { _controller: "JoeZafiroBundle:Canales:index" }

canales_show:
    pattern:  /{id}/show
    defaults: { _controller: "JoeZafiroBundle:Canales:show" }

canales_new:
    pattern:  /new
    defaults: { _controller: "JoeZafiroBundle:Canales:new" }

canales_create:
    pattern:  /create
    defaults: { _controller: "JoeZafiroBundle:Canales:create" }
    requirements: { _method: post }

canales_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "JoeZafiroBundle:Canales:edit" }

canales_update:
    pattern:  /{id}/update
    defaults: { _controller: "JoeZafiroBundle:Canales:update" }
    requirements: { _method: post|put }

canales_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JoeZafiroBundle:Canales:delete" }
    requirements: { _method: post|delete }
