forwardeos:
    pattern:  /
    defaults: { _controller: "JoeZafiroBundle:Forwardeos:index" }

forwardeos_show:
    pattern:  /{id}/show
    defaults: { _controller: "JoeZafiroBundle:Forwardeos:show" }

forwardeos_new:
    pattern:  /new
    defaults: { _controller: "JoeZafiroBundle:Forwardeos:new" }

forwardeos_create:
    pattern:  /create
    defaults: { _controller: "JoeZafiroBundle:Forwardeos:create" }
    requirements: { _method: post }

forwardeos_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "JoeZafiroBundle:Forwardeos:edit" }

forwardeos_update:
    pattern:  /{id}/update
    defaults: { _controller: "JoeZafiroBundle:Forwardeos:update" }
    requirements: { _method: post|put }

forwardeos_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JoeZafiroBundle:Forwardeos:delete" }
    requirements: { _method: post|delete }
