interfaces:
    pattern:  /
    defaults: { _controller: "JoeZafiroBundle:Interfaces:index" }

interfaces_show:
    pattern:  /{id}/show
    defaults: { _controller: "JoeZafiroBundle:Interfaces:show" }

interfaces_new:
    pattern:  /new
    defaults: { _controller: "JoeZafiroBundle:Interfaces:new" }

interfaces_create:
    pattern:  /create
    defaults: { _controller: "JoeZafiroBundle:Interfaces:create" }
    requirements: { _method: post }

interfaces_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "JoeZafiroBundle:Interfaces:edit" }

interfaces_update:
    pattern:  /{id}/update
    defaults: { _controller: "JoeZafiroBundle:Interfaces:update" }
    requirements: { _method: post|put }

interfaces_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JoeZafiroBundle:Interfaces:delete" }
    requirements: { _method: post|delete }
